name: "Security Status Monitoring Action"
description: "This action update CosmosDB with latest repo details."
branding:
  icon: "alert-circle"
  color: "blue"
permissions:
  contents: read
inputs:
  githubToken: # Github Token
    description: "Github token"
    required: true
  db_endpoint: # CosmosDB endpoint url
    description: "CosmosDB endpoint url"
    required: true
  db_key: # CosmosDB key
    description: "Cosmos DB key"
    required: true

outputs:
  time: # id of output
    description: "The time process end"
runs:
  using: "node16"
  main: "dist/index.js"
