name: "Example JavaScript github action"
description: "Write workflow status to database"
permissions:
  contents: read
inputs:
  githubToken: # Github Token
    description: "Github token"
    required: true
  db_endpoint: # CosmosDB endpoint url
    description: "CosmosDB endpoint url"
    required: true
  db_key: # CosmosDB key
    description: "Cosmos DB key"
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
