name: "Security Status Monitoring Action"
description: "This action update CosmosDB with latest repo details."
branding:
  icon: "alert-circle"
  color: "blue"
permissions:
  contents: read
inputs:
  githubToken: # Github Token
    description: "Github token"
    required: true
  db_endpoint: # CosmosDB Base URL
    description: "CosmosDB Base URL"
    required: true
  db_key: # CosmosDB Primary Key
    description: "Cosmos DB Primary Key"
    required: true

outputs:
  time: # id of output
    description: "The time process end"
runs:
  using: "node16"
  main: "dist/index.js"
