name: "Example JavaScript github action"
description: "Write workflow status to database"
permissions:
  contents: read
inputs:
  githubToken: # Github Token 
    description: "Github token"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
